# Generated by Django 4.2 on 2023-04-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year_released',
        ),
        migrations.AddField(
            model_name='album',
            name='artwork',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
