# Generated by Django 4.2 on 2023-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_api', '0002_remove_album_year_released_album_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.IntegerField(blank=True),
        ),
    ]
